return {{[ [[Busy]] ] = false,[ [[Group]] ] = {2},[ [[Spells]] ] = {3},[ [[Classes]] ] = {4},[ [[AutoSpells]] ] = {5},[ [[Tabs]] ] = {6},[ [[SpellQueue]] ] = {7},[ [[IntroCompleted]] ] = true,},
{[ [[Zaver]] ] = [[paladin]],[ [[Mand]] ] = [[cryomancer]],[ [[Choak]] ] = [[druid]],},
{[ [[illumination]] ] = {8},[ [[bone armor]] ] = {9},[ [[decay]] ] = {10},[ [[call lightning]] ] = {11},[ [[dispel good]] ] = {12},[ [[identify]] ] = {13},[ [[stone skin]] ] = {14},[ [[dispel evil]] ] = {15},[ [[fear]] ] = {16},[ [[firestorm]] ] = {17},[ [[full heal]] ] = {18},[ [[wings of heaven]] ] = {19},[ [[positive field]] ] = {20},[ [[entangle]] ] = {21},[ [[magic missile]] ] = {22},[ [[illusory wall]] ] = {23},[ [[phosphoric embers]] ] = {24},[ [[bless]] ] = {25},[ [[supernova]] ] = {26},[ [[shocking grasp]] ] = {27},[ [[harm]] ] = {28},[ [[immolate]] ] = {29},[ [[energy drain]] ] = {30},[ [[enhance ability]] ] = {31},[ [[soul tap]] ] = {32},[ [[wings of hell]] ] = {33},[ [[silence]] ] = {34},[ [[mesmerize]] ] = {35},[ [[cone of cold]] ] = {36},[ [[mirage]] ] = {37},[ [[detect alignment]] ] = {38},[ [[remove curse]] ] = {39},[ [[protection from evil]] ] = {40},[ [[rain]] ] = {41},[ [[create food]] ] = {42},[ [[coldshield]] ] = {43},[ [[resurrect]] ] = {44},[ [[negate cold]] ] = {45},[ [[sunray]] ] = {46},[ [[fire darts]] ] = {47},[ [[ventriloquate]] ] = {48},[ [[destroy undead]] ] = {49},[ [[darkness]] ] = {50},[ [[elemental warding]] ] = {51},[ [[burning hands]] ] = {52},[ [[writhing weeds]] ] = {53},[ [[fireshield]] ] = {54},[ [[detect magic]] ] = {55},[ [[waterform]] ] = {56},[ [[cure critic]] ] = {57},[ [[barkskin]] ] = {58},[ [[major globe]] ] = {59},[ [[heal]] ] = {60},[ [[divine ray]] ] = {61},[ [[prayer]] ] = {62},[ [[vigorize serious]] ] = {63},[ [[flame blade]] ] = {64},[ [[meteorswarm]] ] = {65},[ [[negate heat]] ] = {66},[ [[mass invisibility]] ] = {67},[ [[acid fog]] ] = {68},[ [[dispel magic]] ] = {69},[ [[harness]] ] = {70},[ [[enchant weapon]] ] = {71},[ [[reduce]] ] = {72},[ [[wall of ice]] ] = {73},[ [[insanity]] ] = {74},[ [[divine bolt]] ] = {75},[ [[vicious mockery]] ] = {76},[ [[dragons health]] ] = {77},[ [[circle of light]] ] = {78},[ [[hysteria]] ] = {79},[ [[cause light]] ] = {80},[ [[locate object]] ] = {81},[ [[natures embrace]] ] = {82},[ [[web]] ] = {83},[ [[summon]] ] = {84},[ [[chain lightning]] ] = {85},[ [[cure blind]] ] = {86},[ [[cure serious]] ] = {87},[ [[enlightenment]] ] = {88},[ [[ice shards]] ] = {89},[ [[magic torch]] ] = {90},[ [[natures guidance]] ] = {91},[ [[protection from good]] ] = {92},[ [[lightning bolt]] ] = {93},[ [[acid burst]] ] = {94},[ [[bigbys clenched fist]] ] = {95},[ [[relocate]] ] = {96},[ [[enlarge]] ] = {97},[ [[unholy word]] ] = {98},[ [[misdirection]] ] = {99},[ [[summon corpse]] ] = {100},[ [[degeneration]] ] = {101},[ [[cause serious]] ] = {102},[ [[earth blessing]] ] = {103},[ [[glory]] ] = {104},[ [[disintegrate]] ] = {105},[ [[detonation]] ] = {106},[ [[simulacrum]] ] = {107},[ [[group heal]] ] = {108},[ [[disease]] ] = {109},[ [[holy word]] ] = {110},[ [[flood]] ] = {111},[ [[cure light]] ] = {112},[ [[word of recall]] ] = {113},[ [[vigorize light]] ] = {114},[ [[moonbeam]] ] = {115},[ [[phantasm]] ] = {116},[ [[pyre]] ] = {117},[ [[remove paralysis]] ] = {118},[ [[sense life]] ] = {119},[ [[cause critical]] ] = {120},[ [[remove poison]] ] = {121},[ [[infravision]] ] = {122},[ [[cloud of daggers]] ] = {123},[ [[bone draw]] ] = {124},[ [[exorcism]] ] = {125},[ [[wizard eye]] ] = {126},[ [[charm person]] ] = {127},[ [[minor globe]] ] = {128},[ [[cremate]] ] = {129},[ [[lesser exorcism]] ] = {130},[ [[rebuke undead]] ] = {131},[ [[fracture]] ] = {132},[ [[lesser endurance]] ] = {133},[ [[blindness]] ] = {134},[ [[severance]] ] = {135},[ [[control weather]] ] = {136},[ [[endurance]] ] = {137},[ [[waterwalk]] ] = {138},[ [[create water]] ] = {139},[ [[shift corpse]] ] = {140},[ [[ice dagger]] ] = {141},[ [[farsee]] ] = {142},[ [[teleport]] ] = {143},[ [[vigorize critic]] ] = {144},[ [[night vision]] ] = {145},[ [[cloak of gaia]] ] = {146},[ [[fly]] ] = {147},[ [[color spray]] ] = {148},[ [[animate dead]] ] = {149},[ [[sane mind]] ] = {150},[ [[creeping doom]] ] = {151},[ [[iron maiden]] ] = {152},[ [[hellfire and brimstone]] ] = {153},[ [[demonskin]] ] = {154},[ [[preserve]] ] = {155},[ [[fireball]] ] = {156},[ [[dark presence]] ] = {157},[ [[blur]] ] = {158},[ [[curse]] ] = {159},[ [[invigorate]] ] = {160},[ [[divine essence]] ] = {161},[ [[major paralysis]] ] = {162},[ [[moonwell]] ] = {163},[ [[hell bolt]] ] = {164},[ [[circle of fire]] ] = {165},[ [[iceball]] ] = {166},[ [[demonic aspect]] ] = {167},[ [[armor]] ] = {168},[ [[flamestrike]] ] = {169},[ [[familiarity]] ] = {170},[ [[minor creation]] ] = {171},[ [[earthquake]] ] = {172},[ [[haste]] ] = {173},[ [[speak in tongues]] ] = {174},[ [[reveal hidden]] ] = {175},[ [[ice armor]] ] = {176},[ [[soulshield]] ] = {177},[ [[freezing wind]] ] = {178},[ [[chill touch]] ] = {179},[ [[spinechiller]] ] = {180},[ [[confusion]] ] = {181},[ [[world teleport]] ] = {182},[ [[greater endurance]] ] = {183},[ [[extinguish]] ] = {184},[ [[melt]] ] = {185},[ [[nightmare]] ] = {186},[ [[invisibility]] ] = {187},[ [[sleep]] ] = {188},[ [[greater vitality]] ] = {189},[ [[dark feast]] ] = {190},[ [[vitality]] ] = {191},[ [[ice darts]] ] = {192},[ [[urban renewal]] ] = {193},[ [[heavens gate]] ] = {194},[ [[ice storm]] ] = {195},[ [[discorporate]] ] = {196},[ [[demonic mutation]] ] = {197},[ [[detect poison]] ] = {198},[ [[ray of enfeeblement]] ] = {199},[ [[stygian eruption]] ] = {200},[ [[concealment]] ] = {201},[ [[wandering woods]] ] = {202},[ [[freeze]] ] = {203},[ [[smoke]] ] = {204},[ [[full harm]] ] = {205},[ [[levitate]] ] = {206},[ [[detect invisibility]] ] = {207},[ [[dimension door]] ] = {208},[ [[minor paralysis]] ] = {209},[ [[armor of gaia]] ] = {210},[ [[word of command]] ] = {211},[ [[poison]] ] = {212},[ [[soul reaver]] ] = {213},[ [[hell gate]] ] = {214},[ [[banish]] ] = {215},[ [[group armor]] ] = {216},[ [[nourishment]] ] = {217},[ [[create spring]] ] = {218},[ [[isolation]] ] = {219},},
{[ [[Dru]] ] = [[druid]],[ [[Ant]] ] = [[anti-paladin]],[ [[Pal]] ] = [[paladin]],[ [[Thi]] ] = [[thief]],[ [[Ran]] ] = [[ranger]],[ [[Pyr]] ] = [[pyromancer]],[ [[Mer]] ] = [[mercenary]],[ [[Dia]] ] = [[diabolist]],[ [[War]] ] = [[warrior]],[ [[Pri]] ] = [[priest]],[ [[Nec]] ] = [[necromancer]],[ [[Bar]] ] = [[bard]],[ [[Ass]] ] = [[assassin]],[ [[Ber]] ] = [[berserker]],[ [[Cry]] ] = [[cryomancer]],[ [[Ill]] ] = [[illusionist]],[ [[Mon]] ] = [[monk]],},
{[ [[major globe]] ] = {220},[ [[detect magic]] ] = {221},[ [[coldshield]] ] = {222},[ [[stone skin]] ] = {223},[ [[bone armor]] ] = {224},[ [[ice armor]] ] = {225},[ [[invisibility]] ] = {226},},
{[ [[Zaver]] ] = [[paladin]],},
{},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[The magical light fades away.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {227},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[protection]],[ [[fade_message]] ] = [[Your skin returns to normal.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {228},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {229},[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {230},[ [[sphere]] ] = [[air]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {231},[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {232},[ [[sphere]] ] = [[divination]],[ [[min_position]] ] = [[sitting]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[protection]],[ [[count]] ] = 4,[ [[fade_message]] ] = [[Your skin softens and returns to normal.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {233},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {234},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your courage returns to you.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {235},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {236},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {237},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your wings gently fold back and fade away.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {238},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[earth]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {239},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You break free of the vines.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {240},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {241},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[generic]],[ [[fade_message]] ] = [[The wall dissolves into tiny motes of light...]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {242},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {243},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You feel less righteous.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {244},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {245},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[air]],[ [[count]] ] = 4,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {246},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {247},[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {248},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {249},[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[count]] ] = 2,[ [[fade_message]] ] = [[You feel less enhanced.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {250},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {251},[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your wings gently fold back and fade away.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {252},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You can speak again.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {253},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You regain your senses.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {254},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 2,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {255},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[fade_message]] ] = [[You become more visible as the heat around your body dies out.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {256},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[divination]],[ [[fade_message]] ] = [[You feel less aware.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {257},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {258},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[protection]],[ [[fade_message]] ] = [[You feel less protected.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {259},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {260},[ [[sphere]] ] = [[water]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {261},[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[sitting]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 1,[ [[fade_message]] ] = [[The ice formation around your body melts.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {262},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {263},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[protection]],[ [[count]] ] = 2,[ [[fade_message]] ] = [[You feel vulnerable to the cold again.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {264},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[fade_message]] ] = [[Your vision has returned.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {265},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {266},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {267},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {268},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[The magical darkness lifts.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {269},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[protection]],[ [[fade_message]] ] = [[You feel less safe from the elements.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {270},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {271},[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {272},[ [[sphere]] ] = [[earth]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[fire]],[ [[fade_message]] ] = [[The flames around your body dissipate.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {273},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[divination]],[ [[count]] ] = 1,[ [[fade_message]] ] = [[The detect magic wears off.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {274},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 2,[ [[fade_message]] ] = [[Your form solidifies into flesh once again.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {275},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {276},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[protection]],[ [[fade_message]] ] = [[Your skin softens back to its original texture.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {277},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[protection]],[ [[count]] ] = 3,[ [[fade_message]] ] = [[The globe of force surrounding you dissipates.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {278},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {279},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {280},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your holy prayer fades.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {281},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {282},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {283},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {284},[ [[sphere]] ] = [[earth]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[protection]],[ [[fade_message]] ] = [[Your immunity to heat has passed.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {285},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {286},[ [[sphere]] ] = [[enchantment]],[ [[count]] ] = 1,},
{[ [[Classes]] ] = {287},[ [[sphere]] ] = [[earth]],},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[generic]],[ [[count]] ] = 1,[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {288},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[generic]],[ [[fade_message]] ] = [[The harnessed power in your body fades.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {289},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {290},[ [[sphere]] ] = [[enchantment]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You return to your normal size.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {291},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 2,[ [[fade_message]] ] = [[The wall of ice melts away...]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {292},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your mind returns to reality.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {293},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {294},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {295},[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your health returns to normal.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {296},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[The circle of light above you fades out.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {297},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your courage returns to you.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {298},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {299},[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[divination]],[ [[count]] ] = 1,[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {300},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Nature releases you from her embrace.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {301},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {302},[ [[sphere]] ] = [[enchantment]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {303},[ [[sphere]] ] = [[summoning]],[ [[ok_in_combat]] ] = [[no]],[ [[min_position]] ] = [[standing]],},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[air]],[ [[count]] ] = 2,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {304},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {305},[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {306},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[divination]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {307},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 4,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {308},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[summoning]],[ [[fade_message]] ] = [[Your magic torch peters out.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {309},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You suddenly feel a little unguided.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {310},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {311},[ [[sphere]] ] = [[protection]],},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[air]],[ [[count]] ] = 4,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {312},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {313},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {314},[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[summoning]],[ [[count]] ] = 1,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {315},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You return to your normal size.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {316},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {317},[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You no longer feel like you're going every which way at once.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {318},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {319},[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {320},[ [[sphere]] ] = [[death]],[ [[ok_in_combat]] ] = [[yes]],[ [[min_position]] ] = [[standing]],},
{[ [[Classes]] ] = {321},[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You feel less righteous.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {322},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your visage becomes plain once again.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {323},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {324},[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[earth]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {325},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {326},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {327},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You are cured of your disease!]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {328},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {329},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 5,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {330},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {331},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {332},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {333},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {334},[ [[sphere]] ] = [[water]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {335},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {336},[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {337},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[divination]],[ [[fade_message]] ] = [[You feel less aware of your surroundings.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {338},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {339},[ [[sphere]] ] = [[healing]],},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {340},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[divination]],[ [[fade_message]] ] = [[Your night vision seems to fade.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {341},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {342},[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {343},[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {344},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {345},[ [[sphere]] ] = [[divination]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You feel more self-confident.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {346},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[protection]],[ [[fade_message]] ] = [[The globe around your body fades out.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {347},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {348},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {349},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {350},[ [[sphere]] ] = [[enchantment]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {351},[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your endurance returns to normal.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {352},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You feel a cloak of blindness dissolve.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {353},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {354},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {355},[ [[sphere]] ] = [[enchantment]],},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your endurance returns to normal.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {356},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[count]] ] = 1,[ [[fade_message]] ] = [[Your feet seem less buoyant.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {357},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {358},[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[sitting]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {359},[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[summoning]],[ [[count]] ] = 1,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {360},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[divination]],[ [[count]] ] = 1,[ [[fade_message]] ] = [[Your pupils dilate as your vision returns to normal.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {361},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[summoning]],[ [[count]] ] = 1,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {362},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {363},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your night vision fades out.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {364},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[protection]],[ [[fade_message]] ] = [[Your shroud of nature dissolves.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {365},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[count]] ] = 1,[ [[fade_message]] ] = [[You feel the weight of your body return.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {366},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {367},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {368},[ [[sphere]] ] = [[death]],[ [[ok_in_combat]] ] = [[no]],[ [[min_position]] ] = [[standing]],},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {369},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {370},[ [[sphere]] ] = [[earth]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {371},[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {372},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[protection]],[ [[fade_message]] ] = [[Your skin reverts back to normal.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {373},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {374},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {375},[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You feel the dark presence leave you.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {376},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[The world solidifies as your vision unblurs, and you]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {377},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You feel more optimistic.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {378},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {379},[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {380},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your muscles regain feeling.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {381},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {382},[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {383},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[fire]],[ [[fade_message]] ] = [[The flames surrounding the area die out.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {384},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 5,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {385},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[The demon within you fades away.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {386},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[protection]],[ [[fade_message]] ] = [[You feel less protected.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {387},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {388},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your familiar disguise melts away.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {389},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[summoning]],[ [[count]] ] = 1,[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {390},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[earth]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {391},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[count]] ] = 2,[ [[fade_message]] ] = [[Your pulse returns to normal.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {392},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[divination]],[ [[fade_message]] ] = [[Your vocabulary diminishes drastically.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {393},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {394},[ [[sphere]] ] = [[divination]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[protection]],[ [[count]] ] = 1,[ [[fade_message]] ] = [[Your iced encasing melts away, leaving you vulnerable ]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {395},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[protection]],[ [[fade_message]] ] = [[The aura guarding your body fades away.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {396},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[air]],[ [[count]] ] = 3,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {397},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 4,[ [[fade_message]] ] = [[You feel your strength return.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {398},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {399},[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[yes]],[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You no longer feel so confused.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {400},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[summoning]],[ [[count]] ] = 1,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {401},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your endurance returns to normal.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {402},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 1,[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {403},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {404},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {405},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[count]] ] = 2,[ [[fade_message]] ] = [[You fade back into view.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {406},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You feel less tired.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {407},[ [[aggressive]] ] = true,},
{[ [[Classes]] ] = {408},[ [[sphere]] ] = [[enchantment]],},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {409},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your endurance returns to normal.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {410},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 5,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {411},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[The woods in the surrounding area break apart and crumble.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {412},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {413},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 2,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {414},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[generic]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {415},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You mutate back to your original form.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {416},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[divination]],[ [[fade_message]] ] = [[You feel slightly less aware.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {417},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[count]] ] = 2,[ [[fade_message]] ] = [[Your strength returns to you.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {418},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {419},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[count]] ] = 1,[ [[fade_message]] ] = [[You fade back into view.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {420},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[The woods around you shift back to their proper form.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {421},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[water]],[ [[count]] ] = 9,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {422},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[fire]],[ [[fade_message]] ] = [[As the smoke clears, your vision returns.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {423},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {424},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You float back to the ground.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {425},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[divination]],[ [[count]] ] = 2,[ [[fade_message]] ] = [[Your eyes stop tingling.]],[ [[min_position]] ] = [[sitting]],[ [[Classes]] ] = {426},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[summoning]],[ [[count]] ] = 2,[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {427},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[Your muscles regain feeling.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {428},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {429},[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {430},[ [[sphere]] ] = [[generic]],[ [[ok_in_combat]] ] = [[no]],[ [[min_position]] ] = [[standing]],},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[You feel less sick.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {431},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[death]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {432},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {433},[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[yes]],[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {434},[ [[aggressive]] ] = true,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[protection]],[ [[fade_message]] ] = [[You feel less protected.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {435},[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {436},[ [[sphere]] ] = [[healing]],[ [[min_position]] ] = [[sitting]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[Classes]] ] = {437},[ [[sphere]] ] = [[summoning]],[ [[min_position]] ] = [[standing]],[ [[ok_in_combat]] ] = [[no]],[ [[aggressive]] ] = false,},
{[ [[ok_in_combat]] ] = [[no]],[ [[sphere]] ] = [[enchantment]],[ [[fade_message]] ] = [[It is as if a veil has lifted from the surrounding area.]],[ [[min_position]] ] = [[standing]],[ [[Classes]] ] = {438},[ [[aggressive]] ] = false,},
{[ [[auto]] ] = true,[ [[refreshing]] ] = false,},
{[ [[auto]] ] = false,[ [[refreshing]] ] = false,},
{[ [[auto]] ] = false,[ [[refreshing]] ] = false,},
{[ [[auto]] ] = false,[ [[refreshing]] ] = false,},
{[ [[auto]] ] = false,[ [[refreshing]] ] = false,},
{[ [[auto]] ] = true,[ [[refreshing]] ] = false,},
{[ [[auto]] ] = false,[ [[refreshing]] ] = false,},
{[ [[cleric]] ] = true,[ [[druid]] ] = true,[ [[priest]] ] = true,[ [[illusionist]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[diabolist]] ] = true,[ [[anti-paladin]] ] = true,[ [[cleric]] ] = true,},
{[ [[sorcerer]] ] = true,[ [[bard]] ] = true,[ [[necromancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[priest]] ] = true,[ [[paladin]] ] = true,[ [[cleric]] ] = true,},
{[ [[bard]] ] = true,[ [[illusionist]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[cleric]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,},
{[ [[priest]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[bard]] ] = true,[ [[illusionist]] ] = true,[ [[sorcerer]] ] = true,[ [[ranger]] ] = true,[ [[necromancer]] ] = true,},
{[ [[bard]] ] = true,[ [[illusionist]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[priest]] ] = true,[ [[paladin]] ] = true,[ [[cleric]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[sorcerer]] ] = true,[ [[ranger]] ] = true,[ [[bard]] ] = true,[ [[cryomancer]] ] = true,},
{[ [[cleric]] ] = true,[ [[anti-paladin]] ] = true,[ [[bard]] ] = true,[ [[druid]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[diabolist]] ] = true,},
{[ [[cleric]] ] = true,[ [[priest]] ] = true,[ [[bard]] ] = true,[ [[diabolist]] ] = true,},
{[ [[bard]] ] = true,[ [[illusionist]] ] = true,},
{[ [[cryomancer]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[diabolist]] ] = true,[ [[ranger]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,[ [[cleric]] ] = true,},
{[ [[priest]] ] = true,[ [[paladin]] ] = true,[ [[cleric]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[druid]] ] = true,[ [[priest]] ] = true,[ [[anti-paladin]] ] = true,[ [[paladin]] ] = true,[ [[cleric]] ] = true,},
{[ [[cryomancer]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[cleric]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[bard]] ] = true,[ [[illusionist]] ] = true,},
{[ [[cleric]] ] = true,[ [[priest]] ] = true,},
{[ [[diabolist]] ] = true,[ [[druid]] ] = true,[ [[cleric]] ] = true,},
{[ [[diabolist]] ] = true,[ [[druid]] ] = true,[ [[priest]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[sorcerer]] ] = true,[ [[bard]] ] = true,[ [[necromancer]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[cleric]] ] = true,[ [[necromancer]] ] = true,[ [[pyromancer]] ] = true,[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[illusionist]] ] = true,[ [[diabolist]] ] = true,[ [[sorcerer]] ] = true,[ [[priest]] ] = true,[ [[cryomancer]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[paladin]] ] = true,[ [[diabolist]] ] = true,[ [[ranger]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,},
{[ [[ranger]] ] = true,[ [[druid]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[priest]] ] = true,[ [[paladin]] ] = true,[ [[diabolist]] ] = true,[ [[cleric]] ] = true,},
{[ [[priest]] ] = true,},
{[ [[priest]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,[ [[cleric]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[illusionist]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[paladin]] ] = true,[ [[cleric]] ] = true,[ [[anti-paladin]] ] = true,[ [[pyromancer]] ] = true,[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[illusionist]] ] = true,[ [[diabolist]] ] = true,[ [[sorcerer]] ] = true,[ [[priest]] ] = true,[ [[cryomancer]] ] = true,},
{[ [[sorcerer]] ] = true,},
{[ [[bard]] ] = true,},
{[ [[bard]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[diabolist]] ] = true,[ [[bard]] ] = true,[ [[illusionist]] ] = true,},
{[ [[priest]] ] = true,},
{[ [[bard]] ] = true,},
{[ [[cleric]] ] = true,[ [[priest]] ] = true,},
{[ [[priest]] ] = true,},
{[ [[illusionist]] ] = true,},
{[ [[bard]] ] = true,[ [[priest]] ] = true,[ [[anti-paladin]] ] = true,[ [[diabolist]] ] = true,[ [[cleric]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[illusionist]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[bard]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[diabolist]] ] = true,[ [[druid]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,},
{[ [[sorcerer]] ] = true,[ [[cryomancer]] ] = true,},
{[ [[druid]] ] = true,[ [[paladin]] ] = true,[ [[cleric]] ] = true,[ [[anti-paladin]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[paladin]] ] = true,[ [[diabolist]] ] = true,[ [[ranger]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,},
{[ [[priest]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[illusionist]] ] = true,},
{[ [[ranger]] ] = true,},
{[ [[diabolist]] ] = true,[ [[anti-paladin]] ] = true,},
{[ [[cryomancer]] ] = true,[ [[druid]] ] = true,[ [[sorcerer]] ] = true,[ [[ranger]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[sorcerer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[bard]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[diabolist]] ] = true,[ [[anti-paladin]] ] = true,[ [[cleric]] ] = true,},
{[ [[illusionist]] ] = true,},
{[ [[necromancer]] ] = true,[ [[anti-paladin]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[bard]] ] = true,[ [[priest]] ] = true,[ [[anti-paladin]] ] = true,[ [[diabolist]] ] = true,[ [[cleric]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[bard]] ] = true,[ [[illusionist]] ] = true,},
{[ [[sorcerer]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[illusionist]] ] = true,},
{[ [[cleric]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,},
{[ [[diabolist]] ] = true,},
{[ [[priest]] ] = true,[ [[paladin]] ] = true,[ [[cleric]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[paladin]] ] = true,[ [[diabolist]] ] = true,[ [[ranger]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,},
{[ [[diabolist]] ] = true,[ [[druid]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,[ [[cleric]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[illusionist]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[priest]] ] = true,[ [[paladin]] ] = true,[ [[diabolist]] ] = true,[ [[cleric]] ] = true,},
{[ [[cleric]] ] = true,[ [[ranger]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,},
{[ [[bard]] ] = true,[ [[priest]] ] = true,[ [[anti-paladin]] ] = true,[ [[diabolist]] ] = true,[ [[cleric]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[priest]] ] = true,[ [[paladin]] ] = true,[ [[diabolist]] ] = true,[ [[cleric]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,[ [[illusionist]] ] = true,},
{[ [[bard]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[priest]] ] = true,},
{[ [[sorcerer]] ] = true,},
{[ [[bard]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[priest]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[diabolist]] ] = true,[ [[druid]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,},
{[ [[illusionist]] ] = true,[ [[cleric]] ] = true,[ [[anti-paladin]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,},
{[ [[illusionist]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[diabolist]] ] = true,[ [[druid]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,},
{[ [[druid]] ] = true,[ [[cleric]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,[ [[cryomancer]] ] = true,},
{[ [[druid]] ] = true,[ [[priest]] ] = true,[ [[anti-paladin]] ] = true,[ [[paladin]] ] = true,[ [[cleric]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[illusionist]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,[ [[cleric]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[sorcerer]] ] = true,[ [[bard]] ] = true,[ [[illusionist]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[priest]] ] = true,[ [[bard]] ] = true,[ [[diabolist]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[diabolist]] ] = true,},
{[ [[diabolist]] ] = true,[ [[anti-paladin]] ] = true,},
{[ [[diabolist]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,[ [[necromancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[diabolist]] ] = true,[ [[anti-paladin]] ] = true,},
{[ [[ranger]] ] = true,},
{[ [[bard]] ] = true,[ [[anti-paladin]] ] = true,},
{[ [[bard]] ] = true,[ [[druid]] ] = true,},
{[ [[priest]] ] = true,},
{[ [[bard]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[diabolist]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[diabolist]] ] = true,},
{[ [[priest]] ] = true,[ [[paladin]] ] = true,[ [[cleric]] ] = true,},
{[ [[cleric]] ] = true,},
{[ [[bard]] ] = true,[ [[illusionist]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[diabolist]] ] = true,[ [[druid]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[diabolist]] ] = true,[ [[priest]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[illusionist]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[paladin]] ] = true,[ [[cleric]] ] = true,[ [[anti-paladin]] ] = true,[ [[diabolist]] ] = true,[ [[priest]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[illusionist]] ] = true,[ [[sorcerer]] ] = true,[ [[ranger]] ] = true,[ [[necromancer]] ] = true,},
{[ [[necromancer]] ] = true,},
{[ [[bard]] ] = true,[ [[illusionist]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[diabolist]] ] = true,[ [[druid]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[illusionist]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[illusionist]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[illusionist]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[cleric]] ] = true,[ [[priest]] ] = true,},
{[ [[diabolist]] ] = true,},
{[ [[cleric]] ] = true,[ [[priest]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[priest]] ] = true,},
{[ [[sorcerer]] ] = true,[ [[cryomancer]] ] = true,},
{[ [[illusionist]] ] = true,},
{[ [[diabolist]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[paladin]] ] = true,[ [[diabolist]] ] = true,[ [[priest]] ] = true,[ [[cleric]] ] = true,[ [[necromancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[diabolist]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[cryomancer]] ] = true,},
{[ [[pyromancer]] ] = true,},
{[ [[cleric]] ] = true,[ [[priest]] ] = true,[ [[diabolist]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[illusionist]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[illusionist]] ] = true,[ [[sorcerer]] ] = true,[ [[necromancer]] ] = true,},
{[ [[pyromancer]] ] = true,[ [[cryomancer]] ] = true,[ [[bard]] ] = true,[ [[sorcerer]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[diabolist]] ] = true,[ [[priest]] ] = true,},
{[ [[druid]] ] = true,[ [[bard]] ] = true,[ [[cleric]] ] = true,[ [[anti-paladin]] ] = true,[ [[diabolist]] ] = true,[ [[necromancer]] ] = true,},
{[ [[illusionist]] ] = true,},
{[ [[diabolist]] ] = true,},
{[ [[diabolist]] ] = true,},
{[ [[cleric]] ] = true,[ [[priest]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[druid]] ] = true,},
{[ [[illusionist]] ] = true,},
}